/*
    This file has been autogenerated using [generate_version_header.py].
    This file may be overwritten.
*/
#ifndef _VERSION_HPP_
#define _VERSION_HPP_

static const char* FRAMEWORK_VERSION = "v3.2.0-46-g6e799d83d";
static const char* PROJECT_VERSION = "v3.2.0-46-g6e799d83d";

#endif

